[colors.bright]
black = "#353535"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.cursor]
cursor = "#E8E3E3"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#8DA3B9"
cyan = "#8AA6A2"
green = "#8C977D"
magenta = "#A988B0"
red = "#B66467"
white = "#E8E3E3"
yellow = "#D9BC8C"

[colors.primary]
background = "#1b1b19"
foreground = "#E8E3E3"

