import = [
	"~/.config/alacritty/themes/catppuccin_frappe.toml",
	"~/.config/alacritty/fonts/jetbrains.toml",
]

[cursor]
thickness = 0.2
smooth_motion = true
smooth_motion_factor = 0.8
smooth_motion_spring = 0.5
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"

[window]
opacity = 0.85
title = "Alacritty"

[window.padding]
x = 5
y = 5

